
export const strategems = [
    {
        "name": "Anti-Materiel Rifle",
        "icon": "/strategems/Anti-Materiel Rifle.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Anti-Personnel Minefield",
        "icon": "/strategems/Anti-Personnel Minefield.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Arc Thrower",
        "icon": "/strategems/Arc Thrower.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Autocannon Sentry",
        "icon": "/strategems/Autocannon Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Autocannon",
        "icon": "/strategems/Autocannon.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": true,
    },
    {
        "name": "Ballistic Shield Backpack",
        "icon": "/strategems/Ballistic Shield Backpack.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Eagle 110MM Rocket Pods",
        "icon": "/strategems/Eagle 110MM Rocket Pods.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle 500KG Bomb",
        "icon": "/strategems/Eagle 500KG Bomb.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle Airstrike",
        "icon": "/strategems/Eagle Airstrike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle Cluster Bomb",
        "icon": "/strategems/Eagle Cluster Bomb.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle Napalm Airstrike",
        "icon": "/strategems/Eagle Napalm Airstrike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle Smoke Strike",
        "icon": "/strategems/Eagle Smoke Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Eagle Strafing Run",
        "icon": "/strategems/Eagle Strafing Run.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "EMS Mortar Sentry",
        "icon": "/strategems/EMS Mortar Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Expendable Anti-Tank",
        "icon": "/strategems/Expendable Anti-Tank.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Flamethrower",
        "icon": "/strategems/Flamethrower.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Gatling Sentry",
        "icon": "/strategems/Gatling Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Grenade Launcher",
        "icon": "/strategems/Grenade Launcher.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Guard Dog Rover",
        "icon": "/strategems/Guard Dog Rover.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Guard Dog",
        "icon": "/strategems/Guard Dog.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Heavy Machine Gun",
        "icon": "/strategems/Heavy Machine Gun.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "HMG Emplacement",
        "icon": "/strategems/HMG Emplacement.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Incendiary Mines",
        "icon": "/strategems/Incendiary Mines.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Jump Pack",
        "icon": "/strategems/Jump Pack.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Laser Cannon",
        "icon": "/strategems/Laser Cannon.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Machine Gun Sentry",
        "icon": "/strategems/Machine Gun Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Machine Gun",
        "icon": "/strategems/Machine Gun.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Mortar Sentry",
        "icon": "/strategems/Mortar Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital 120MM HE Barrage",
        "icon": "/strategems/Orbital 120MM HE Barrage.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital 380MM HE Barrage",
        "icon": "/strategems/Orbital 380MM HE Barrage.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Airburst Strike",
        "icon": "/strategems/Orbital Airburst Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital EMS Strike",
        "icon": "/strategems/Orbital EMS Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Gas Strike",
        "icon": "/strategems/Orbital Gas Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Gatling Barrage",
        "icon": "/strategems/Orbital Gatling Barrage.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Laser",
        "icon": "/strategems/Orbital Laser.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Precision Strike",
        "icon": "/strategems/Orbital Precision Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Railcannon Strike",
        "icon": "/strategems/Orbital Railcannon Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Smoke Strike",
        "icon": "/strategems/Orbital Smoke Strike.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Orbital Walking Barrage",
        "icon": "/strategems/Orbital Walking Barrage.svg",
        "category": "Offensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Patriot Exosuit",
        "icon": "/strategems/Patriot Exosuit.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Quasar Cannon",
        "icon": "/strategems/Quasar Cannon.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Railgun",
        "icon": "/strategems/Railgun.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Recoilless Rifle",
        "icon": "/strategems/Recoilless Rifle.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": true,
    },
    {
        "name": "Rocket Sentry",
        "icon": "/strategems/Rocket Sentry.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Shield Generator Pack",
        "icon": "/strategems/Shield Generator Pack.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Shield Generator Relay",
        "icon": "/strategems/Shield Generator Relay.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    },
    {
        "name": "Spear",
        "icon": "/strategems/Spear.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": true,
    },
    {
        "name": "Stalwart",
        "icon": "/strategems/Stalwart.svg",
        "category": "Supply",
        "backpack": false,
        "support_weapon": true,
    },
    {
        "name": "Supply Pack",
        "icon": "/strategems/Supply Pack.svg",
        "category": "Supply",
        "backpack": true,
        "support_weapon": false,
    },
    {
        "name": "Tesla Tower",
        "icon": "/strategems/Tesla Tower.svg",
        "category": "Defensive",
        "backpack": false,
        "support_weapon": false,
    }
  ]